# Generated by Django 5.2.9 on 2025-12-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='color_code',
            field=models.CharField(default='#3498db', help_text='HEX-код цвета, используемый в годовом календаре (например, #ff5733).', max_length=7, verbose_name='Цвет в графике отпусков'),
        ),
    ]
