# Generated by Django 5.2.9 on 2025-12-03 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет (HEX)')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Оплачиваемый')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Требует подтверждения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип отсутствия',
                'verbose_name_plural': 'Типы отсутствий',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.absencetype', verbose_name='Тип')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_records', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_records', to=settings.AUTH_USER_MODEL, verbose_name='Кто отметил')),
            ],
            options={
                'verbose_name': 'Запись в табеле',
                'verbose_name_plural': 'Записи в табеле',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
